In [8]:
import numpy as np

In [9]:
our_matrix = np.array([[2, 0, -1],
                       [5, 1, 0],
                       [0, 1, 3]])
print(our_matrix)

[[ 2  0 -1]
 [ 5  1  0]
 [ 0  1  3]]


In [10]:
inverse_matrix = np.linalg.inv(our_matrix)

print(inverse_matrix)

[[  3.  -1.   1.]
 [-15.   6.  -5.]
 [  5.  -2.   2.]]


In [11]:
singular_matrix = np.array([[3, 4],
                            [6, 8]])

inverse_singular_matrix = np.linalg.inv(singular_matrix)

print(inverse_singular_matrix)

LinAlgError: ignored